using System;

namespace kasthack.vksharp.DataTypes.Enums {
    [Flags]
    public enum UserFields:long {
        About = 1L << 0,
        Activities = 1L << 1,
        Anything = 1L << 51,
        Bdate = 1L << 2,
        Blacklisted = 1L << 3,
        Books = 1L << 4,
        CanPost = 1L << 5,
        CanSeeAllPosts = 1L << 6,
        CanSeeAudio = 1L << 7,
        CanWritePrivateMessage = 1L << 8,
        Career = 1L << 58,
        City = 1L << 9,
        CommonCount = 1L << 10,
        Connections = 1L << 11,
        Contacts = 1L << 12,
        Counters = 1L << 13,
        Country = 1L << 14,
        CropPhoto = 1L << 55,
        Domain = 1L << 15,
        Education = 1L << 16,
        Everything = ~0L,
        Exports = 1L << 17,
        FollowersCount = 1L << 18,
        FriendStatus = 1L << 57,
        Games = 1L << 19,
        HasMobile = 1L << 20,
        HasPhoto = 1L << 60,
        HomeTown = 1L << 21,
        Interests = 1L << 22,
        IsFavorite = 1L << 59,
        IsFriend = 1L << 56,
        LastSeen = 1L << 23,
        Lists = 1L << 24,
        MaidenName = 1L << 52,
        Military = 1L << 54,
        Movies = 1L << 25,
        Music = 1L << 26,
        Nickname = 1L << 27,
        None = 0L,
        Occupation = 1L << 50,
        Online = 1L << 28,
        Personal = 1L << 29,
        Photo100 = 1L << 30,
        Photo200 = 1L << 31,
        Photo200Orig = 1L << 32,
        Photo400Orig = 1L << 33,
        Photo50 = 1L << 34,
        PhotoId = 1L << 53,
        PhotoMax = 1L << 35,
        PhotoMaxOrig = 1L << 36,
        Quotes = 1L << 37,
        Relation = 1L << 38,
        Relatives = 1L << 39,
        Schools = 1L << 40,
        ScreenName = 1L << 49,
        Sex = 1L << 41,
        Site = 1L << 42,
        Status = 1L << 43,
        Timezone = 1L << 44,
        Tv = 1L << 45,
        Universities = 1L << 46,
        Verified = 1L << 47,
        WallComments = 1L << 48,
        CanSendFriendRequest=1L<<61,
        IsHiddenFromFeed=1L<<62,
        BlacklistedByMe=1L<<63
    }
}
